/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CurriculoRouteImport } from './routes/curriculo'
import { Route as ExportRouteImport } from './routes/export'
import { Route as FeatureFlagsRouteImport } from './routes/feature-flags'
import { Route as GamificationRouteImport } from './routes/gamification'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntelligenceDashboardRouteImport } from './routes/intelligence-dashboard'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as LocalSystemsRouteImport } from './routes/local-systems'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RealizacoesRouteImport } from './routes/realizacoes'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoRoute = CurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsRoute = FeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationRoute = GamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceDashboardRoute = IntelligenceDashboardRouteImport.update({
  id: '/intelligence-dashboard',
  path: '/intelligence-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSystemsRoute = LocalSystemsRouteImport.update({
  id: '/local-systems',
  path: '/local-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RealizacoesRoute = RealizacoesRouteImport.update({
  id: '/realizacoes',
  path: '/realizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/curriculo': typeof CurriculoRoute
  '/export': typeof ExportRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/gamification': typeof GamificationRoute
  '/insights': typeof InsightsRoute
  '/intelligence-dashboard': typeof IntelligenceDashboardRoute
  '/jogos': typeof JogosRoute
  '/local-systems': typeof LocalSystemsRoute
  '/planejamento': typeof PlanejamentoRoute
  '/projetos': typeof ProjetosRoute
  '/realizacoes': typeof RealizacoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/curriculo': typeof CurriculoRoute
  '/export': typeof ExportRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/gamification': typeof GamificationRoute
  '/insights': typeof InsightsRoute
  '/intelligence-dashboard': typeof IntelligenceDashboardRoute
  '/jogos': typeof JogosRoute
  '/local-systems': typeof LocalSystemsRoute
  '/planejamento': typeof PlanejamentoRoute
  '/projetos': typeof ProjetosRoute
  '/realizacoes': typeof RealizacoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/curriculo': typeof CurriculoRoute
  '/export': typeof ExportRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/gamification': typeof GamificationRoute
  '/insights': typeof InsightsRoute
  '/intelligence-dashboard': typeof IntelligenceDashboardRoute
  '/jogos': typeof JogosRoute
  '/local-systems': typeof LocalSystemsRoute
  '/planejamento': typeof PlanejamentoRoute
  '/projetos': typeof ProjetosRoute
  '/realizacoes': typeof RealizacoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/auth'
    | '/configuracoes'
    | '/curriculo'
    | '/export'
    | '/feature-flags'
    | '/gamification'
    | '/insights'
    | '/intelligence-dashboard'
    | '/jogos'
    | '/local-systems'
    | '/planejamento'
    | '/projetos'
    | '/realizacoes'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/auth'
    | '/configuracoes'
    | '/curriculo'
    | '/export'
    | '/feature-flags'
    | '/gamification'
    | '/insights'
    | '/intelligence-dashboard'
    | '/jogos'
    | '/local-systems'
    | '/planejamento'
    | '/projetos'
    | '/realizacoes'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/analytics'
    | '/auth'
    | '/configuracoes'
    | '/curriculo'
    | '/export'
    | '/feature-flags'
    | '/gamification'
    | '/insights'
    | '/intelligence-dashboard'
    | '/jogos'
    | '/local-systems'
    | '/planejamento'
    | '/projetos'
    | '/realizacoes'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CurriculoRoute: typeof CurriculoRoute
  ExportRoute: typeof ExportRoute
  FeatureFlagsRoute: typeof FeatureFlagsRoute
  GamificationRoute: typeof GamificationRoute
  InsightsRoute: typeof InsightsRoute
  IntelligenceDashboardRoute: typeof IntelligenceDashboardRoute
  JogosRoute: typeof JogosRoute
  LocalSystemsRoute: typeof LocalSystemsRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  ProjetosRoute: typeof ProjetosRoute
  RealizacoesRoute: typeof RealizacoesRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo': {
      id: '/curriculo'
      path: '/curriculo'
      fullPath: '/curriculo'
      preLoaderRoute: typeof CurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags': {
      id: '/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof FeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification': {
      id: '/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof GamificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence-dashboard': {
      id: '/intelligence-dashboard'
      path: '/intelligence-dashboard'
      fullPath: '/intelligence-dashboard'
      preLoaderRoute: typeof IntelligenceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-systems': {
      id: '/local-systems'
      path: '/local-systems'
      fullPath: '/local-systems'
      preLoaderRoute: typeof LocalSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realizacoes': {
      id: '/realizacoes'
      path: '/realizacoes'
      fullPath: '/realizacoes'
      preLoaderRoute: typeof RealizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CurriculoRoute: CurriculoRoute,
  ExportRoute: ExportRoute,
  FeatureFlagsRoute: FeatureFlagsRoute,
  GamificationRoute: GamificationRoute,
  InsightsRoute: InsightsRoute,
  IntelligenceDashboardRoute: IntelligenceDashboardRoute,
  JogosRoute: JogosRoute,
  LocalSystemsRoute: LocalSystemsRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  ProjetosRoute: ProjetosRoute,
  RealizacoesRoute: RealizacoesRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
